
const state={products:[],cart:JSON.parse(localStorage.getItem('vanta2Cart')||'[]'),wishlist:JSON.parse(localStorage.getItem('vanta2Wish')||'[]')};
const save=()=>{localStorage.setItem('vanta2Cart',JSON.stringify(state.cart));localStorage.setItem('vanta2Wish',JSON.stringify(state.wishlist));count()};
const count=()=>{const e=document.getElementById('cartCount');if(e)e.textContent=state.cart.reduce((n,x)=>n+x.qty,0)};
const toast=m=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1100)};
const addToCart=id=>{const x=state.cart.find(i=>i.id===id);x?x.qty++:state.cart.push({id,qty:1});save();toast('Added to bag')};
const toggleWish=id=>{state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();toast('Saved pieces updated')};
const card=p=>`<article class="card"><div class="badge">${p.id%2===0?'SIGNATURE':'NEW'}</div><button class="wish" onclick="toggleWish(${p.id})">♡</button><a class="photo" href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.image_alt||p.name}" loading="lazy"></a><div class="info"><div class="rating">★★★★★ <span>(${p.reviews})</span></div><h3>${p.name}</h3><div class="meta">${p.room} · ${p.benefit}</div><div class="row"><strong>$${Number(p.price).toFixed(2)}</strong><button onclick="addToCart(${p.id})">Add to Bag</button></div></div></article>`;
async function load(){state.products=await (await fetch('products.json')).json();setup();renderShop();renderProduct();renderCart();renderWish();count()}
function setup(){const c=document.getElementById('catFilter'),r=document.getElementById('roomFilter');if(c)[...new Set(state.products.map(p=>p.category))].sort().forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;c.appendChild(o)});if(r)[...new Set(state.products.map(p=>p.room))].sort().forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;r.appendChild(o)});['shopSearch','catFilter','roomFilter','sort'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderShop));document.getElementById('search')?.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='shop.html?search='+encodeURIComponent(e.target.value)})}
function renderShop(){const g=document.getElementById('shopGrid');if(!g)return;const q=new URLSearchParams(location.search);const search=(document.getElementById('shopSearch')?.value||q.get('search')||'').toLowerCase();const cat=document.getElementById('catFilter')?.value||q.get('cat')||'';const room=document.getElementById('roomFilter')?.value||q.get('room')||'';const sort=document.getElementById('sort')?.value||'featured';let a=state.products.filter(p=>(!search||(p.name+' '+p.category+' '+p.room+' '+p.benefit).toLowerCase().includes(search))&&(!cat||p.category===cat)&&(!room||p.room===room));if(sort==='price-low')a.sort((x,y)=>x.price-y.price);if(sort==='price-high')a.sort((x,y)=>y.price-x.price);if(sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name));g.innerHTML=a.map(card).join('')}
function renderProduct(){const e=document.getElementById('productDetail');if(!e)return;const id=Number(new URLSearchParams(location.search).get('id')||0);const p=state.products.find(x=>x.id===id)||state.products[0];e.innerHTML=`<div class="detail"><div class="detail-photo"><img src="${p.image}" alt="${p.image_alt||p.name}"></div><div class="detail-info"><div class="eyebrow">${p.category}</div><h1>${p.name}</h1><div class="rating">★★★★★ (${p.reviews})</div><div class="price">$${Number(p.price).toFixed(2)}</div><p>${p.description}</p><div class="specs"><div class="spec"><small>Room</small><strong>${p.room}</strong></div><div class="spec"><small>SKU</small><strong>${p.sku}</strong></div><div class="spec"><small>Availability</small><strong>In Stock</strong></div><div class="spec"><small>Collection</small><strong>${p.category}</strong></div></div><div class="note">${p.details}</div><button class="btn" onclick="addToCart(${p.id})">Add to Bag</button> <a class="ghostBtn" href="contact.html">Ask Support</a></div></div>`}
function renderCart(){const e=document.getElementById('cartPage');if(!e)return;if(!state.cart.length){e.innerHTML='<p>Your bag is empty.</p><a class="btn dark" href="shop.html">Keep Shopping →</a>';return}let total=0,rows='';for(const i of state.cart){const p=state.products.find(x=>x.id===i.id);if(!p)continue;total+=p.price*i.qty;rows+=`<div class="cartRow"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><div>Qty ${i.qty}</div></div><b>$${(p.price*i.qty).toFixed(2)}</b><button onclick="state.cart=state.cart.filter(x=>x.id!==${i.id});save();renderCart()">Remove</button></div>`}e.innerHTML=rows+`<h2>Total: $${total.toFixed(2)}</h2><button class="btn dark" onclick="toast('Checkout demo')">Checkout</button>`}
function renderWish(){const e=document.getElementById('wishlistPage');if(!e)return;const a=state.products.filter(p=>state.wishlist.includes(p.id));e.innerHTML=a.length?`<div class="productGrid">${a.map(card).join('')}</div>`:'<p>No saved pieces yet.</p>'}
load();
